version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            - pip install pylint==2.4.4 pytest coverage
            - pip install -r requirements.txt
    pre_build:
        commands:
            - echo "[+] Running Pylint..."
            - find . -type f -name "*.py" | xargs pylint --exit-zero
    build:
        commands:
            - echo "[+] Installing python dependencies...."
            - pip install -r requirements.txt -t ./package
            - cd package
            - zip -r9 ${OLDPWD}/src/function.zip .
            - cd ${OLDPWD}/src
            - zip -g function.zip lambda_function.py
            - zip -g function.zip response.py
            - echo "[+] Deploying to Lambda...."
            - aws lambda update-function-code --function-name justreportit --region=us-west-2 --zip-file fileb://function.zip